name: "TestSystem Build"

on: [push]

jobs:
build:
runs-on: windows-latest
  steps:
  - uses: actions/checkout@master

  - name: Setup .NET Core SDK
    uses: actions/setup-dotnet@v1
    with:
    dotnet-version: '3.1'

  - name: Restore
    run: dotnet restore

  - name: Build
    run: dotnet build --no-restore

  - name: Publish app for deploy
    run: dotnet publish ./TestSystem/TestSystem.csproj -c Release -o ${{env.DOTNET_ROOT}}/published

  - name: 'Deploy to Azure WebApp'
    uses: azure/webapps-deploy@v1
    with:
      app-name: 'TestSystemASP'
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      package: ${{env.DOTNET_ROOT}}/published

