name: TestSystem Build

on: [push]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'

    - name: Build
      run: dotnet build ./ASP/TestSystem/TestSystem.csproj --configuration Release

    - name: Publish app for deploy
      run: dotnet publish ./ASP/TestSystem/TestSystem.csproj -c Release -o ${{env.DOTNET_ROOT}}/published

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'TestSystemASP'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{env.DOTNET_ROOT}}/published

